---
title: "p8105_hw4_jma2249.Rmd"
author: "Josie Alford"
date: "10/30/2017"
output: html_document
---
```{r Load Packages, warning = FALSE, message = FALSE}
library(tidyverse)
library(haven)
library(janitor)
library(dplyr)
library(ggplot2)
library(lubridate)
```

#Problem Two
```{r Dem & GOP, warning = FALSE, message = FALSE}
#Read and Clean data in pols-month.csv
politicians_data = read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>%
  clean_names() %>%
  mutate(mon = floor_date(mon, "month")) %>%
  separate(mon, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(month = month.name[month]) %>%
  rename(gop = prez_gop, dem = prez_dem) %>%
  mutate(gop = replace(gop, gop == 2, 1)) %>%
  mutate(president = recode(gop, '0' = "dem", '1' = "gop")) %>% 
  select(-dem, -gop, -day, -gov_gop, -gov_dem, -sen_gop, -sen_dem, -rep_dem, -rep_gop)
politicians_data #Loaded and Tidied
```

```{r GDP, warning = FALSE, message = FALSE}
gdp_data = read_csv("./data/fivethirtyeight_datasets/GDP.csv") %>%
  clean_names() %>%
  mutate(date = floor_date(date, "month")) %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(month = month.name[month]) %>%
  select(-day)%>%
  rename(gdp = value) %>%
  mutate(gdp = as.numeric(gdp))
gdp_data #Loaded and Tidied
```


```{r Join Datasets, warning = FALSE, message = FALSE}
combined_538 = gdp_data %>% 
  left_join(politicians_data) %>% 
  filter(!is.na(gdp)) %>% 
  mutate(
    quarter = recode(month, January = "Q1", April = "Q2", July = "Q3", October = "Q4")
    ) %>% 
  select(-month) %>% 
  unite(qtr, c(year, quarter))
combined_538
```

#Collaborator: MeOak!
```{r Plot of GDP & Presidential Party Overtime, warning = FALSE, message = FALSE}
###############
#For your reference, here are a couple of links to ones in "real life" :) Take your pick xx https://www.bea.gov/newsreleases/national/gdp/gdp_glance.htm and https://data.oecd.org/gdp/real-gdp-forecast.htm#indicator-chart
##############


##############
#bar plot
##############
combined_538 %>% 
  ggplot(aes(x = qtr, y = gdp, fill = president)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values=c("blue", "red")) 
```